=== rogergerberquirino93502/magento02-docker/app/code/Firebear/ImportExport/etc/format_files.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * @copyright: Copyright Â© 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="fileFormat" type="fileFormatDeclaration" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="fileFormatDeclaration">
        <xs:annotation>
            <xs:documentation>
                Export file format declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="direction" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="model" type="modelName" use="optional" />
    </xs:complexType>

    <xs:simpleType name="modelName">
        <xs:annotation>
            <xs:documentation>
                Model name can contain only [A-Za-z_\d\\\\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_\d\\\\]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rogergerberquirino93502/magento02-docker/app/code/Firebear/ImportExport/etc/format_files.xml
<?xml version="1.0"?>
<!--
/**
 * @copyright: Copyright Â© 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Firebear_ImportExport:etc/format_files.xsd">
    <fileFormat name="csv" direction="import" label="CSV" model="Firebear\ImportExport\Model\Import\Source\Csv" />
    <fileFormat name="xml" direction="import" label="XML" model="Firebear\ImportExport\Model\Import\Source\Xml" />
    <fileFormat name="json" direction="import" label="JSON" model="Firebear\ImportExport\Model\Import\Source\Json" />
    <fileFormat name="ods" direction="import" label="ODS" model="Firebear\ImportExport\Model\Import\Source\Ods" />
    <fileFormat name="xlsx" direction="import" label="XLSX" model="Firebear\ImportExport\Model\Import\Source\Xlsx" />
   <!-- <fileFormat name="txt" direction="import" label="TXT" model="Firebear\ImportExport\Model\Import\Source\Txt" />-->
    <fileFormat name="csv" direction="export" label="CSV" model="Firebear\ImportExport\Model\Export\Adapter\Csv" />
    <fileFormat name="xml" direction="export" label="XML" model="Firebear\ImportExport\Model\Export\Adapter\Xml" />
    <fileFormat name="ods" direction="export" label="ODS" model="Firebear\ImportExport\Model\Export\Adapter\Ods" />
    <fileFormat name="google" direction="export" label="Google Sheet" model="Firebear\ImportExport\Model\Export\Adapter\GoogleSheet" />
    <fileFormat name="xlsx" direction="export" label="XLSX" model="Firebear\ImportExport\Model\Export\Adapter\Xlsx" />
    <fileFormat name="json" direction="export" label="JSON" model="Firebear\ImportExport\Model\Export\Adapter\Json" />
<!--    <fileFormat name="txt" direction="export" label="TXT" model="Firebear\ImportExport\Model\Export\Adapter\Txt" />-->
</config>
