=== rogergerberquirino93502/magento02-docker/app/code/Divante/VsbridgeIndexerCore/etc/vsbridge_indices.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="indices">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="index" type="indexDefinition" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="indexDefinition">
        <xs:sequence>
            <xs:element name="type" type="typeDefinition" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="identifier" use="required"/>
    </xs:complexType>

    <xs:complexType name="typeDefinition">
        <xs:all>
            <xs:element name="data_providers" type="dataProvidersDefinition" minOccurs="0"/>
        </xs:all>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="mapping" use="optional"/>
    </xs:complexType>

    <xs:complexType name="dataProvidersDefinition">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="data_provider" type="dataProviderDefinition"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dataProviderDefinition">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== rogergerberquirino93502/magento02-docker/app/code/Divante/VsbridgeIndexerCatalog/etc/vsbridge_indices.xml
<indices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Divante_VsbridgeIndexerCore:etc/vsbridge_indices.xsd">

    <index identifier="vue_storefront_catalog">
        <type name="product" mapping="Divante\VsbridgeIndexerCatalog\Index\Mapping\Product">
            <data_providers>
                <data_provider name="attributes">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\AttributeData</data_provider>
                <data_provider name="bundle_options_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\BundleOptionsData</data_provider>
                <data_provider name="category_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\CategoryData</data_provider>
                <data_provider name="price_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\PriceData</data_provider>
                <data_provider name="media_gallery">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\MediaGalleryData</data_provider>
                <data_provider name="link_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\ProductLinksData</data_provider>
                <data_provider name="inventory_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\Inventory</data_provider>
                <data_provider name="configurable_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\ConfigurableData</data_provider>
                <data_provider name="custom_options">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\CustomOptions</data_provider>
            </data_providers>
        </type>
        <type name="category" mapping="Divante\VsbridgeIndexerCatalog\Index\Mapping\Category">
            <data_providers>
                <data_provider name="category_data">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Category\AttributeData</data_provider>
            </data_providers>
        </type>
        <type name="attribute" mapping="Divante\VsbridgeIndexerCatalog\Index\Mapping\Attribute">
            <data_providers>
                <data_provider name="options">Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Attribute\Options</data_provider>
            </data_providers>
        </type>
    </index>
</indices>
